### ISSUE TITLE
Boolean native type support for  gnostic-go-generator

### ISSUE THREAD

**Issue by sebidude** [googleapis/gnostic#104]
Hi all,
Thanks for the tool.  
When generating a type from a schema which states a boolean property, the generator for golang produces a "Boolean" instead of "bool" native type.

```yaml
components:    
  schemas:
    agent:
      type: object
      required:
        - name
        - active
      properties:
        name:
          type: string
          minLength: 4
          readOnly: true
        active:
          type: boolean
```

With this spec, the generator creates types.go which contains the following:
```golang
// implements the service definition of agent
type Agent struct {
	Name   string  `json:"name,omitempty"`
	Active Boolean `json:"active,omitempty"`
}
```
So "Boolean" is not the native golang type.
