### ISSUE TITLE
Extension handlers only handle extensions with "object" type.

### ISSUE THREAD

**Issue by timburks** [googleapis/gnostic#34]
While testing extensions with a real-world schema, I discovered that extensions of array and scalar types were not being handled. Here's a schema that illustrates the problem:

```
title: "JSON schema for apis.guru extensions"
$schema: "http://json-schema.org/draft-04/schema#"
type: object
definitions:
  Logo:
    type: object
    id: x-logo
    required:
    - url
    properties:
      url:
        type: string
        format: url
  APIClientRegistration:
    type: object
    id: x-apiClientRegistration
    required:
    - url
    properties:
      url:
        type: string
        format: url
  Origin:
    id: x-origin
    type: object
    required:
    - format
    - url
    - version
    properties:
      format:
        type: string
      url:
        type: string
        format: url
      version:
        type: string
  Preferred:
    id: x-preferred
    type: boolean
  ProviderName:
    id: x-providerName
    type: string
  ServiceName:
    id: x-serviceName
    type: string
  APISGuruCategories:
    id: x-apisguru-categories
    type: array
  Tags:
    id: x-tags
    type: array
  UnofficialSpec:
    id: x-unofficialSpec
    type: boolean
```
